data:
  batch_size: 512
  data_root_dir: data
  dataset: vqa_2.0
  image_depth_first: false
  image_fast_reader: true
  image_feat_test:
  - detectron/fc6/vqa/test2015
  image_feat_train:
  - detectron/fc6/vqa/train2014
  - detectron/fc6/vqa/val2014
  image_feat_val:
  - detectron/fc6/vqa/val2014
  image_max_loc: 100
  imdb_file_test:
  - imdb/imdb_test2015.npy
  imdb_file_train:
  - imdb/imdb_train2014.npy
  - imdb/imdb_val2train2014.npy
  imdb_file_val:
  - imdb/imdb_minival2014.npy
  num_workers: 5
  question_max_len: 14
  vocab_answer_file: answers_vqa.txt
  vocab_question_file: vocabulary_vqa.txt
exp_name: baseline
loss: softmaxKL
model:
  classifier:
    method: linear_classifier
    par: {}
  image_embedding_models:
  - modal_combine:
      method: MFH
      par:
        dropout: 0.1
        hidden_sizes:
        - 5000
        - 5000
        order: 2
        pool_size: 5
    normalization: softmax
    transform:
      method: conv_transform
      par:
        hidden_dim: 512
        out_dim: 2
  image_feat_dim: 2048
  image_feature_encoding:
  - method: finetune_faster_rcnn_fpn_fc7
    par:
      bias_file: detectron/fc6/fc7_b.pkl
      weights_file: detectron/fc6/fc7_w.pkl
  modal_combine:
    method: MFH
    par:
      dropout: 0.1
      hidden_sizes:
      - 5000
      - 5000
      order: 2
      pool_size: 5
  question_embedding:
  - method: att_que_embed
    par:
      LSTM_hidden_size: 1024
      LSTM_layer: 1
      conv1_out: 512
      conv2_out: 2
      dropout: 0
      embedding_dim: 300
      embedding_init_file: vqa2.0_glove.6B.300d.txt.npy
      kernel_size: 1
      padding: 0
optimizer:
  method: Adamax
  par:
    eps: 1.0e-08
    lr: 0.01
    weight_decay: 0
run: train+predict
training_parameters:
  clip_norm_mode: all
  lr_ratio: 0.1
  lr_steps:
  - 5000
  - 7000
  - 9000
  - 11000
  max_grad_l2_norm: 0.25
  max_iter: 12000
  report_interval: 100
  snapshot_interval: 1000
  wu_factor: 0.2
  wu_iters: 1000
