includes:
- common/defaults/configs/datasets/vqa/vqa2.yml
model_attributes:
  ban:
    metrics:
    - vqa_accuracy
    losses:
    - type: logit_bce
    text_embedding:
      num_hidden: 1280
      vocab_size: 1280
      emb_size: 300
      num_layers: 1
      dropout: 0.0
      bidirectional: False
      rnn_type: 'GRU'
    bilinear_attention:
      bc_net:
        k: 1
        dropout: [0.2, 0.5]
        h_out:
      fc_net:
        dims: 600
        activation:
        dropout: 0.2
      gamma: 4
      visual_feat_dim: 2048
    classifier:
      # out dim will be taken from registry as set by dataset builder
      hidden_size: 600
      dropout: 0.5
optimizer_attributes:
  type: Adamax
  params:
    eps: 1.0e-08
    lr: 0.01
    weight_decay: 0
training_parameters:
  clip_norm_mode: all
  clip_gradients: true
  lr_ratio: 0.1
  lr_scheduler: true
  lr_steps:
  - 15000
  - 18000
  - 20000
  - 21000
  max_grad_l2_norm: 0.25
  max_iterations: 22000
  use_warmup: true
  warmup_factor: 0.2
  warmup_iterations: 1000
  patience: 4000
  batch_size: 512
  num_workers: 7
  task_size_proportional_sampling: true
  monitored_metric: vqa2/vqa_accuracy
  metric_minimize: false
