includes:
- ../projects/vilbert/configs/masked_conceptual_captions/pretrain.yaml

dataset_config:
  masked_conceptual_captions:
    annotations:
      train:
      - cc/defaults/annotations/train_small_10_pc.npy
