includes:
- ../projects/visual_bert/configs/masked_coco/pretrain.yaml

dataset_config:
  masked_coco:
    annotations:
      train:
      - coco/defaults/annotations/imdb_karpathy_train_by_image_10_pc.npy
