dataset_config:
  visual_entailment:
      data_dir: ${env.data_dir}/datasets
      depth_first: false
      fast_read: false
      use_images: false
      use_features: true
      zoo_requirements:
      - flickr30k.defaults
      - visual_entailment.defaults
      images:
        train:
        - flickr30k/defaults/images/flickr30k_images
        val:
        - flickr30k/defaults/images/flickr30k_images
        test:
        - flickr30k/defaults/images/flickr30k_images
      features:
        train:
        - flickr30k/defaults/features/detectron.lmdb
        val:
        - flickr30k/defaults/features/detectron.lmdb
        test:
        - flickr30k/defaults/features/detectron.lmdb
      annotations:
        train:
        - visual_entailment/defaults/annotations/snli_ve_train.jsonl
        val:
        - visual_entailment/defaults/annotations/snli_ve_dev.jsonl
        test:
        - visual_entailment/defaults/annotations/snli_ve_test.jsonl
      max_features: 100
      processors:
        text_processor:
          type: vocab
          params:
            max_length: 14
            vocab:
              type: intersected
              embedding_name: glove.6B.300d
              vocab_file: visual_entailment/defaults/extras/vocabs/vocabulary_100k.txt
            preprocessor:
              type: simple_sentence
              params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 50
      return_features_info: false
      # Return OCR information
      use_ocr: false
      # Return spatial information of OCR tokens if present
      use_ocr_info: false
