includes:
- configs/datasets/hateful_memes/bert.yaml

model_config:
  mmf_transformer:
    training_head_type: classification
    num_labels: 2
    heads:
      - type: refiner_classifier
        refiner_config:
          type: refiner
          freeze: false
          lr_multiplier: 1.0
          hidden_size: 768
          vocab_size: 30522
          loss_type: "ms"
          modalities:
            - "text"
            - "image"
          weights:
            - 0.1
            - 0.1
          refiner_target_pooling:
            type: average_k_from_last
            k: 1
        mlp_config:
          type: mlp
          freeze: false
          num_labels: 2
          lr_multiplier: 1.0
          hidden_size: 768
          vocab_size: 30522
          loss: cross_entropy
          max_sample_size: 2
        ms_loss_weight: 0.1
        use_msloss: true
    self_weight_decay: 0.997

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
    metrics:
    - accuracy
    - binary_f1
    - roc_auc

training:
  batch_size: 32
  lr_scheduler: true
  max_updates: 22000
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false

checkpoint:
  pretrained_state_mapping:
    pooler: pooler
    backend.transformer: backend.transformer
    backend.embeddings: backend.embeddings
