dataset_config:
  okvqa:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: true
    use_features: false
    zoo_requirements:
    - okvqa.defaults
    images:
      train:
      - okvqa/defaults/images/
      val:
      - okvqa/defaults/images/
      test:
      - okvqa/defaults/images/
    features:
      train:
      - okvqa/defaults/features/features_fc6/COCO_trainval2014.lmdb
      val:
      - okvqa/defaults/features/features_fc6/COCO_trainval2014.lmdb
      test:
      - okvqa/defaults/features/features_fc6/COCO_trainval2014.lmdb
    annotations:
      train:
      - okvqa/defaults/annotations/annotations/imdb_train1.npy
      val:
      - okvqa/defaults/annotations/annotations/imdb_val1.npy
      test:
      - okvqa/defaults/annotations/annotations/imdb_test.npy
    max_features: 100
    processors:
      text_processor:
        type: vocab
        params:
          max_length: 14
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: okvqa/defaults/extras/vocabs/vocabulary_100k.txt
          preprocessor:
            type: simple_sentence
            params: {}
      answer_processor:
        type: vqa_answer
        params:
          num_answers: 10
          vocab_file: okvqa/defaults/extras/vocabs/answers_okvqa.txt
          preprocessor:
            type: simple_word
            params: {}
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [256, 256]
            - type: CenterCrop
              params:
                size: [224, 224]
            - ToTensor
            - GrayScaleTo3Channels
            - type: Normalize
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.12221994, 0.12145835, 0.14380469]
      context_processor:
        type: fasttext
        params:
          download_initially: false
          max_length: 50
          model_file: wiki.en.bin
      ocr_token_processor:
        type: simple_word
        params: {}
      bbox_processor:
        type: bbox
        params:
          max_length: 50
    return_features_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
