dataset_config:
  vizwiz:
    return_features_info: true
    use_images: false
    use_features: true
    features:
      train:
      - vizwiz/v2019/features/detectron.lmdb
      - vizwiz/v2019/features/detectron.lmdb
      val:
      - vizwiz/v2019/features/detectron.lmdb
      test:
      - vizwiz/v2019/features/detectron.lmdb
    annotations:
      train:
      - datasets/vizwiz/imdbs/imdb_vizwiz_train.npy
      - datasets/vizwiz/imdbs/imdb_vizwiz_val.npy
    processors:
      # Stop fasttext from loading by overriding the context_processor
      context_processor:
        type: simple_word
        params: {}
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
