dataset_config:
  vqa2:
      data_dir: ${env.data_dir}/datasets
      depth_first: false
      fast_read: false
      use_images: false
      use_features: true
      zoo_requirements:
      - coco.defaults
      - vqa2.defaults
      images:
        train:
        - coco/defaults/images/train2014
        val:
        - coco/defaults/images/val2014
        test:
        - coco/defaults/images/test2015
      features:
        train:
        - coco/defaults/features/trainval2014.lmdb
        val:
        - coco/defaults/features/trainval2014.lmdb
        test:
        - coco/defaults/features/test2015.lmdb
      annotations:
        train:
        - vqa2/defaults/annotations/imdb_train2014.npy
        val:
        - vqa2/defaults/annotations/imdb_val2014.npy
        test:
        - vqa2/defaults/annotations/imdb_test2015.npy
      max_features: 100
      processors:
        text_processor:
          type: vocab
          params:
            max_length: 14
            vocab:
              type: intersected
              embedding_name: glove.6B.300d
              vocab_file: vqa2/defaults/vocabs/vocabulary_100k.txt
            preprocessor:
              type: simple_sentence
              params: {}
        answer_processor:
          type: vqa_answer
          params:
            num_answers: 10
            vocab_file: vqa2/defaults/vocabs/answers_vqa.txt
            preprocessor:
              type: simple_word
              params: {}
        context_processor:
          type: fasttext
          params:
            download_initially: false
            max_length: 50
            model_file: wiki.en.bin
        ocr_token_processor:
          type: simple_word
          params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 50
      return_features_info: false
      # Return OCR information
      use_ocr: false
      # Return spatial information of OCR tokens if present
      use_ocr_info: false
