dataset_config:
  masked_mmimdb:
    data_dir: ${env.data_dir}
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    features:
      train:
      - datasets/mmimdb/defaults/features/features.lmdb
      val:
      - datasets/mmimdb/defaults/features/features.lmdb
      test:
      - datasets/mmimdb/defaults/features/features.lmdb
    annotations:
      train:
      - datasets/mmimdb/defaults/annotations/train.jsonl
      val:
      - datasets/mmimdb/defaults/annotations/dev.jsonl
      test:
      - datasets/mmimdb/defaults/annotations/test.jsonl
    max_features: 100
    use_image_feature_masks: false
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 256
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.90
      transformer_bbox_processor:
          type: transformer_bbox
          params:
            bbox_key: bbox
            image_width_key: image_width
            image_height_key: image_height
    return_features_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
