dataset_config:
  masked_vqa2:
    data_dir: ${env.data_dir}/datasets
    zoo_requirements:
    - coco.defaults
    - vqa2.defaults
    add_answer: true
    use_images: false
    use_features: true
    return_features_info: true
    use_image_feature_masks: true
    max_features: 36
    use_ocr: false
    use_ocr_info: false
    features:
      train:
      - coco/defaults/features/trainval2014.lmdb
      - coco/defaults/features/trainval2014.lmdb
    annotations:
      train:
      - vqa2/defaults/annotations/imdb_train2014.npy
      - vqa2/defaults/annotations/imdb_val2014.npy
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 20
      answer_processor:
        type: vqa_answer
        params:
          num_answers: 10
          vocab_file: vqa2/defaults/extras/vocabs/answers_vqa.txt
          preprocessor:
            type: simple_word
            params: {}
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 20
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.9
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height
      attribute_processor:
        type: vocab
        params:
          max_length: 1
          vocab:
            type: random
            vocab_file: vqa2/defaults/extras/vocabs/vocabulary_100k.txt
