dataset_config:
  masked_gqa:
    data_dir: ${env.data_dir}/datasets
    zoo_requirements:
    - gqa.defaults
    add_answer: true
    use_images: false
    use_features: true
    return_features_info: true
    use_image_feature_masks: true
    max_features: 36
    use_ocr: false
    use_ocr_info: false
    features:
      train:
      - gqa/defaults/features/gqa.lmdb
      - gqa/defaults/features/gqa.lmdb
    annotations:
      train:
      - gqa/defaults/annotations/train_balanced_questions.npy
      - gqa/defaults/annotations/val_balanced_questions.npy
    processors:
      bbox_processor:
        type: bbox
        params:
          max_length: 36
      text_processor:
        type: bert_tokenizer
        params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0.15
            max_seq_length: 20
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 20
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.90
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height
      answer_processor:
        type: vqa_answer
        params:
          num_answers: 10
          vocab_file: gqa/defaults/vocabs/answers_gqa.txt
          preprocessor:
            type: simple_word
            params: {}
