dataset_config:
  detection_visual_genome:
    use_images: true
    zoo_requirements:
    - visual_genome.detection_split_by_coco_2017
    data_dir: ${env.data_dir}/datasets
    images:
      train:
      - visual_genome/detection_split_by_coco_2017/images
      val:
      - visual_genome/detection_split_by_coco_2017/images
      test:
      - visual_genome/detection_split_by_coco_2017/images
    annotations:
      train:
      - visual_genome/detection_split_by_coco_2017/annotations/instances_train_split_by_coco_2017.json
      val:
      - visual_genome/detection_split_by_coco_2017/annotations/instances_val_split_by_coco_2017.json
      test:
      - visual_genome/detection_split_by_coco_2017/annotations/instances_val_split_by_coco_2017.json
    load_attributes: true  # Visual Genome has attribute annotations
    processors:
      detection_image_and_target_processor:
        type: detr_image_and_target
        params:
          train_image_sizes: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
          train_resize_random_sizes: [400, 500, 600]
          train_crop_size: [384, 600]
          test_image_size: 800
          max_size: 1333
    max_target_enc_size: 16382  # maximum number of bytes to encode detection targets into pickle
