includes:
- configs/datasets/mmimdb/with_features.yaml

model_config:
  vilbert:
    training_head_type: classification
    num_labels: 24
    losses:
    - type: logit_bce

dataset_config:
  mmimdb:
    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 256
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: 88000

evaluation:
  metrics:
  - accuracy
  - multilabel_macro_f1
  - multilabel_micro_f1

training:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  find_unused_parameters: true
  early_stop:
    criteria: mmimdb/multilabel_micro_f1
    minimize: false

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
