data:
  data_root_dir: data
  image_feat_test:
  - detectron/fc6/vqa/test2015
  image_feat_train:
  - detectron_23/fc6/vqa/train2014
  - detectron_23/fc6/vqa/val2014
  image_feat_val:
  - detectron_23/fc6/vqa/val2014
  image_max_loc: 100
  imdb_file_test:
  - imdb/imdb_test2015.npy
  imdb_file_train:
  - imdb/imdb_train2014.npy
  - imdb/imdb_val2train2014.npy
  imdb_file_val:
  - imdb/imdb_minival2014.npy
  batch_size: 512
loss: softmaxKL
model:
  image_feature_encoding:
  - method: finetune_faster_rcnn_fpn_fc7
    par:
      weights_file: detectron/fc6/fc7_w.pkl
      bias_file: detectron/fc6/fc7_b.pkl
  classifier:
    method: linear_classifier
  image_embedding_models:
  - modal_combine:
      method: MFH
      par:
        order: 1
        hidden_sizes:
        - 5000
        dropout: 0.1
        pool_size: 5
    normalization: softmax
    transform:
      method: conv_transform
  modal_combine:
    method: MFH
    par:
      order: 2
      hidden_sizes:
      - 5000
      - 5000
      dropout: 0.1
      pool_size: 5
