model_config:
  mmf_transformer:
    training_head_type: classification
    num_labels: 2253
    losses:
    - type: logit_bce

dataset_config:
  okvqa:
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

evaluation:
    metrics:
    - vqa_accuracy

training:
  batch_size: 32
  lr_scheduler: true
  max_updates: 22000
  early_stop:
    criteria: okvqa/vqa_accuracy
    minimize: false

checkpoint:
  pretrained_state_mapping:
    pooler: pooler
    backend.transformer: backend.transformer
    backend.embeddings: backend.embeddings
