model_config:
  mmbt:
    training_head_type: classification
    num_labels: 24
    losses:
    - type: logit_bce

dataset_config:
  mmimdb:
    return_features_info: false
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 256

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
  metrics:
  - accuracy
  - multilabel_macro_f1
  - multilabel_micro_f1

training:
  batch_size: 32
  lr_scheduler: true
  max_updates: 22000
  early_stop:
    criteria: mmimdb/multilabel_micro_f1
    minimize: false

checkpoint:
  pretrained_state_mapping:
    bert: bert
