includes:
- ./defaults.yaml

model_config:
  krisp:
    graph_module:
      kg_path: okvqa/krisp/graphs/cn_graph.pth.tar
      node2vec_filename: okvqa/krisp/node2vec/node2vec_cn.pkl
      graph_vocab_file: okvqa/krisp/graph_vocab/graph_vocab_cn.pth.tar
dataset_config:
  okvqa:
    processors:
      answer_processor:
        params:
          graph_vocab_file: okvqa/krisp/graph_vocab/graph_vocab_cn.pth.tar
