model_config:
  krisp:
    visual_bert:
      hidden_size: 768
      hidden_dropout_prob: 0.1
      training_head_type: classification
      pooler_strategy: vqa
      zerobias: true
    graph_module:
      kg_path: okvqa/defaults/annotations/annotations/graphs/full_graph.pth.tar
      dataset_info_path: okvqa/defaults/annotations/annotations/graph_vocab/okvqa_dataset_info.pth.tar
      embedding_file: okvqa/defaults/annotations/annotations/glove.840B.300d.txt
      node2vec_filename: okvqa/defaults/annotations/annotations/node2vec/node2vec.pkl
      vocab_file: okvqa/defaults/annotations/annotations/answer_vocab_count10.txt
      graph_vocab_file: okvqa/defaults/annotations/annotations/graph_vocab/graph_vocab.pth.tar
      prune_culdesacs: false
      node_inputs:
        question: 1
        classifiers: 4
        w2v: 300
      node_hid_dim: 128
      num_gcn_conv: 2
      use_batch_norm: true
      use_dropout: false
      dropout_p: 0
      output_type: hidden_ans
      gcn_type: RGCN
      num_labels: 2250
      output_order: alpha
      output_special_node: false
      add_ans_nodes: false
    num_labels: 2250
    output_combine: concat
    graph_logit_mode: mc4
    losses:
    - type: logit_bce
    zerobias: true
    feed_graph_to_vb: false
    feed_vb_to_graph: true
    feed_q_to_graph: false
    feed_mode: feed_vb_hid_to_graph
    feed_special_node: false
    topk_ans_feed: 10
    compress_crossmodel: true
    crossmodel_compress_dim: 128
    analysis_mode: false
    noback_vb_to_graph: false
    noback_vb_to_blinear: false
    instance_graph: false
dataset_config:
  okvqa:
    use_images: false
    use_features: true
    return_features_info: true
    zoo_requirements:
    - okvqa.defaults
    - okvqa
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
      answer_processor:
        type: graph_vqa_answer
        params:
          concat_scores: true
          num_answers: 10
          vocab_file: okvqa/defaults/annotations/annotations/answer_vocab_count10.txt
          graph_vocab_file: okvqa/defaults/annotations/annotations/graph_vocab/graph_vocab.pth.tar
          preprocessor:
            type: simple_word
            params: {}
    dump_output_dir: ${env.save_dir}
    dump_pred_info: false
optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8
    weight_decay: 0

scheduler:
  type: warmup_cosine
  params:
    num_warmup_steps: 2000
    num_training_steps: 88000

evaluation:
  metrics:
  - vqa_accuracy

training:
  batch_size: 56
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 88000
  early_stop:
    criteria: okvqa/vqa_accuracy
    minimize: false
  find_unused_parameters: true
checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
    graph_module: graph_module
