includes:
- ./defaults.yaml

model_config:
  krisp:
    graph_module:
      vocab_file: okvqa/defaults/annotations/annotations/answer_vocab_v10_count10.txt
      graph_vocab_file: okvqa/defaults/annotations/annotations/graph_vocab/graph_vocab_v10.pth.tar
      okvqa_v_mode: "v1.0-121"
      old_graph_vocab_file: okvqa/defaults/annotations/annotations/graph_vocab/graph_vocab.pth.tar
      ans_translation_file: okvqa/defaults/annotations/annotations/ans_vocab_tx.pth.tar
      num_labels: 2253
    num_labels: 2253
dataset_config:
  okvqa:
    processors:
      answer_processor:
        params:
          vocab_file: okvqa/defaults/annotations/annotations/answer_vocab_v10_count10.txt
          graph_vocab_file: okvqa/defaults/annotations/annotations/graph_vocab/graph_vocab_v10.pth.tar
