includes:
- ./dbpedia_only.yaml

dataset_config:
  okvqa:
    annotations:
      train:
      - okvqa/defaults/annotations/imdb_trainval.npy
      val:
      - okvqa/defaults/annotations/imdb_test.npy
      test:
      - okvqa/defaults/annotations/imdb_test.npy

