dataset_config:
  masked_gqa:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    zoo_requirements:
    - gqa.defaults
    features:
      train:
      - gqa/defaults/features/gqa.lmdb
      val:
      - gqa/defaults/features/gqa.lmdb
      test:
      - gqa/defaults/features/gqa.lmdb
    annotations:
      train:
      - gqa/defaults/annotations/train_balanced_questions.npy
      val:
      - gqa/defaults/annotations/val_balanced_questions.npy
      test:
      - gqa/defaults/annotations/test_balanced_questions.npy
    max_features: 100
    use_image_feature_masks: false
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 128
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.90
      transformer_bbox_processor:
          type: transformer_bbox
          params:
            bbox_key: bbox
            image_width_key: image_width
            image_height_key: image_height
    return_features_info: true
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
