dataset_config:
  masked_localized_narratives:
    use_ocr: False
    use_ocr_info: False
    data_dir: ${env.data_dir}/datasets
    use_images: False
    use_features: True
    zoo_requirements:
    - localized_narratives.defaults
    features:
      train:
      - flickr30k/defaults/features/detectron.lmdb
      - ade20k/defaults/features/ade20k_train.lmdb
      val:
      - flickr30k/defaults/features/detectron.lmdb
      - ade20k/defaults/features/ade20k_val.lmdb
      test:
      - flickr30k/defaults/features/detectron.lmdb
    annotations:
      train:
      - localized_narratives/defaults/annotations/flickr30k_train_localized_narratives.jsonl
      - localized_narratives/defaults/annotations/ade20k_train_localized_narratives.jsonl
      val:
      - localized_narratives/defaults/annotations/flickr30k_val_localized_narratives.jsonl
      - localized_narratives/defaults/annotations/ade20k_validation_localized_narratives.jsonl
      test:
      - localized_narratives/defaults/annotations/flickr30k_test_localized_narratives.jsonl
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: True
          mask_probability: 0.15
          max_seq_length: 64