includes:
- ./defaults.yaml

dataset_config:
  visual_entailment:
    return_features_info: true
    use_images: false
    use_features: true
    features:
        train:
        - flickr30k/defaults/features/detectron.lmdb
        - flickr30k/defaults/features/detectron.lmdb
        val:
        - flickr30k/defaults/features/detectron.lmdb
        test:
        - flickr30k/defaults/features/detectron.lmdb
    annotations:
        train:
        - visual_entailment/defaults/annotations/snli_ve_train.jsonl
        - visual_entailment/defaults/annotations/snli_ve_dev.jsonl
        val:
        - visual_entailment/defaults/annotations/snli_ve_test.jsonl
        test:
        - visual_entailment/defaults/annotations/snli_ve_test.jsonl
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
