model_config:
  vilbert:
    training_head_type: visual7w
    num_labels: 1
    num_multiple_choices: 4
    losses:
    - type: cross_entropy

optimizer:
  type: adam_w
  params:
    lr: 2e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 200
    num_training_steps: ${training.max_updates}

evaluation:
  metrics:
  - accuracy

training:
  batch_size: 256
  lr_scheduler: true
  max_updates: 2000
  find_unused_parameters: true
  early_stop:
    criteria: visual7w/accuracy
    minimize: false
  evaluation_interval: 360
  evaluate_metrics: true

checkpoint:
  resume_pretrained: true
  resume_zoo: vilbert.pretrained.cc.original 
  pretrained_state_mapping:
    model.bert: model.bert
