dataset_config:
  hateful_memes:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    images:
      val:
      - hateful_memes/defaults/images/
    features:
      val:
      - hateful_memes/defaults/features/detectron.lmdb
    annotations:
      val:
      - hateful_memes/defaults/annotations/train.jsonl
    processors:
      text_processor:
        type: vocab
        params:
          max_length: 52
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: coco/defaults/extras/vocabs/vocabulary_captioning_thresh5.txt
          preprocessor:
            type: simple_sentence
            params: {}
      caption_processor:
        type: caption
        params:
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: coco/defaults/extras/vocabs/vocabulary_captioning_thresh5.txt

      context_processor:
        type: fasttext
        params:
          download_initially: false
          max_length: 50
          model_file: wiki.en.bin
