dataset_config:
  conceptual_captions:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    features:
      train:
      - cc/defaults/features/cc_train.lmdb
      val:
      - cc/defaults/features/cc_val.lmdb
      test:
      - cc/defaults/features/cc_val.lmdb
    annotations:
      train:
      - cc/defaults/annotations/train_all.npy
      val:
      - cc/defaults/annotations/val.npy
      test:
      - cc/defaults/annotations/val.npy
    max_features: 100
    processors:
      text_processor:
        type: vocab
        params:
          max_length: 20
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: cc/defaults/extras/vocabs/vocabulary_conceptual_captioning_thresh5.txt
          preprocessor:
            type: simple_sentence
            params: {}
      caption_processor:
        type: caption
        params:
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: cc/defaults/extras/vocabs/vocabulary_conceptual_captioning_thresh5.txt
    min_captions_per_img: 1
    return_features_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
