dataset_config:
  vizwiz:
      data_dir: ${env.data_dir}/datasets
      depth_first: false
      fast_read: false
      use_images: false
      use_features: true
      zoo_requirements:
      - vizwiz.v2019
      features:
          train:
          - vizwiz/v2019/features/detectron.lmdb
          val:
          - vizwiz/v2019/features/detectron.lmdb
          test:
          - vizwiz/v2019/features/detectron.lmdb
      annotations:
          train:
          - vizwiz/v2019/annotations/imdb_vizwiz_train.npy
          val:
          - vizwiz/v2019/annotations/imdb_vizwiz_val.npy
          test:
          - vizwiz/v2019/annotations/imdb_vizwiz_test.npy
      max_features: 100
      processors:
        text_processor:
          type: vocab
          params:
            max_length: 14
            vocab:
              type: intersected
              embedding_name: glove.6B.300d
              vocab_file: vizwiz/v2019/extras/vocabs/vocabulary_100k.txt
            preprocessor:
              type: simple_sentence
              params: {}
        answer_processor:
          type: vqa_answer
          params:
            vocab_file: vizwiz/v2019/extras/vocabs/answers_vizwiz_7k.txt
            preprocessor:
              type: simple_word
              params: {}
            num_answers: 10
        context_processor:
          type: fasttext
          params:
            max_length: 50
            model_file: wiki.en.bin
        ocr_token_processor:
          type: simple_word
          params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 50
      return_features_info: true
      # Return OCR information
      use_ocr: false
      # Return spatial information of OCR tokens if present
      use_ocr_info: false
