includes:
- ./defaults.yaml

dataset_config:
  vqa2:
    use_images: false
    use_features: true
    features:
      train:
      - coco/defaults/features/trainval2014.lmdb
      val:
      - coco/defaults/features/trainval2014.lmdb
    annotations:
      train:
      - vqa2/defaults/annotations/imdb_debug.npy
      val:
      - vqa2/defaults/annotations/imdb_debug.npy
