includes:
- ./resnet_only.yaml

dataset_config:
  vqa2:
    use_images: false
    use_features: true
    features:
      train:
      - coco/resnet152/features/trainval2014.lmdb
      - coco/resnet152/features/trainval2014.lmdb
      val:
      - coco/resnet152/features/trainval2014.lmdb
      test:
      - coco/resnet152/features/test2015.lmdb
    annotations:
      train:
      - vqa2/defaults/annotations/imdb_train2014.npy
      - vqa2/defaults/annotations/imdb_valminusminival2014.npy
      val:
      - vqa2/defaults/annotations/imdb_minival2014.npy
